# generated by maixhub, tested on maixpy v0.6.0_2_g9720594
# copy files to TF card and plug into board and power on

import sensor, image, lcd, time
import KPU as kpu
import gc, sys
from machine import UART
from fpioa_manager import fm

input_size = (224, 224)
lcd_rotation=0
labels = [1, 0]

# setup uart
fm.register(34, fm.fpioa.UART1_TX)
fm.register(35, fm.fpioa.UART1_RX)
uart = UART(UART.UART1, 115200, 8, None, 1, timeout=1000, read_buf_len=1)

# setup sensor
sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QVGA)
sensor.set_windowing(input_size)
sensor.skip_frames(time = 2000)

clock = time.clock()

try:
    task = None
    task = kpu.load("/sd/model-91412.kmodel")
    while(True):
        img = sensor.snapshot()
        t = time.ticks_ms()
        fmap = kpu.forward(task, img)
        t = time.ticks_ms() - t
        plist=fmap[:]
        pmax=max(plist)
        if pmax > .8:
            max_index=plist.index(pmax)
            out = labels[max_index]
            print(out, pmax)
            uart.write(str(out))
        lcd.display(img)
except Exception as e:
    print(e)
